### ISSUE TITLE
zcu104_vai_custum Build image is switched with hello_dpu Build image

### ISSUE THREAD

**Issue by kevinkit** [hill19850213/vitis_ai_custom_platform_v1.2.1#5]
Under "**Create the Vitis Platform**" step 11:

11. Click zcu104_vai_custom project in the Vitis Explorer view, click the Build button to generate the platform. 

![image](https://raw.githubusercontent.com/hill19850213/vitis_ai_custom_platform_v1.2.1/master/pic_for_readme/build_project.png)

This image is posted where the hello_dpu is clicked, while under:

**Create and Build a Vitis Application**

8. Right click on the src folder under your hello_dpu application in the Expplorer window, and select "Import Sources" 

![image](https://raw.githubusercontent.com/hill19850213/vitis_ai_custom_platform_v1.2.1/master/pic_for_readme/import_sources.png)

The zcu104_vai_custom is clicked in the image.

I assume these two images must be switched and the later image should be moved down to point 21.

**Comment by hill19850213** [comment]
One is for building bitstream and the other one is for building application.

**Comment by kevinkit** [comment]
yes but it is it possible that the images are switched ? cause in the upper image it says "Click zcu104_vai_custom project in the Vitis Explorer view" but the image is showing that it was clicked on "hello_dpu"

**Comment by hill19850213** [comment]
Sorry,it's my fault. I put wrong screenshot for "Import Sources".
